"""add historic matchs v2

Revision ID: 10b7f7d9a74f
Revises: 374f71f17508
Create Date: 2025-07-02 16:11:32.536224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10b7f7d9a74f'
down_revision: Union[str, None] = '374f71f17508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'player1_id')
    op.drop_column('matches', 'player2_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('player1_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('matches', sa.Column('player2_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
