"""add historic match

Revision ID: 374f71f17508
Revises: 93d6029b66f3
Create Date: 2025-07-02 15:45:54.366312

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "374f71f17508"
down_revision: Union[str, None] = "93d6029b66f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tourney_id", sa.String(), nullable=False),
        sa.Column("winner_id", sa.Integer(), nullable=False),
        sa.Column("loser_id", sa.Integer(), nullable=False),
        sa.Column("loser_seed", sa.Integer(), nullable=True),
        sa.Column("winner_seed", sa.Integer(), nullable=True),
        sa.Column("winner_entry", sa.String(), nullable=True),
        sa.Column("loser_entry", sa.String(), nullable=True),
        sa.Column("winner_name", sa.String(), nullable=True),
        sa.Column("loser_name", sa.String(), nullable=True),
        sa.Column("score", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tourney_id", "winner_id", "loser_id", name="_match_uc"),
    )
    op.drop_constraint("joueurs_name_key", "joueurs", type_="unique")
    op.create_unique_constraint("_name_ioc_uc", "joueurs", ["name", "ioc"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_name_ioc_uc", "joueurs", type_="unique")
    op.create_unique_constraint(
        "joueurs_name_key", "joueurs", ["name"], postgresql_nulls_not_distinct=False
    )
    op.drop_table("matches")
    # ### end Alembic commands ###
