"""Create initial tables

Revision ID: 93d6029b66f3
Revises:
Create Date: 2025-06-30 11:37:09.657229

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93d6029b66f3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "joueurs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("hand", sa.String(), nullable=True),
        sa.Column("ht", sa.Integer(), nullable=True),
        sa.Column("ioc", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tournois",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tourney_id", sa.String(), nullable=True),
        sa.Column("tourney_name", sa.String(), nullable=False),
        sa.Column("surface", sa.String(), nullable=True),
        sa.Column("draw_size", sa.Integer(), nullable=True),
        sa.Column("tourney_level", sa.String(), nullable=True),
        sa.Column("tourney_date", sa.Date(), nullable=True),
        sa.Column("tourney_start_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tourney_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tournois")
    op.drop_table("joueurs")
    # ### end Alembic commands ###
