"""avoid seed match

Revision ID: cb08834d0900
Revises: 10b7f7d9a74f
Create Date: 2025-07-02 17:12:42.409436

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb08834d0900"
down_revision: Union[str, None] = "10b7f7d9a74f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "loser_seed")
    op.drop_column("matches", "winner_seed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matches",
        sa.Column("winner_seed", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "matches",
        sa.Column("loser_seed", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
